# Generated by Django 3.0.5 on 2020-04-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(default='', help_text='Book cover image link', max_length=1024, verbose_name='Image URL'),
        ),
    ]
