# Generated by Django 3.0.5 on 2020-06-02 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(blank=True, choices=[('ADJ', 'adjective'), ('ADP', 'adposition'), ('ADV', 'adverb'), ('AUX', 'auxiliary verb'), ('CONJ', 'coordinating conjunction'), ('DET', 'determiner'), ('INTJ', 'interjection'), ('NOUN', 'noun'), ('NUM', 'numeral'), ('PART', 'particle'), ('PRON', 'pronoun'), ('PROPN', 'proper noun'), ('PUNCT', 'punctuation'), ('SCONJ', 'subordinating conjunction'), ('SYM', 'symbol'), ('VERB', 'verb'), ('X', 'other')], default='X', help_text='Tag Type (adjective, verb, noun, etc.)', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='image',
        ),
        migrations.CreateModel(
            name='TemplateTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prompts.Tag')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prompts.Template')),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='template_tag', through='prompts.TemplateTag', to='prompts.Tag'),
        ),
        migrations.AddField(
            model_name='prompt',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prompts.Template'),
        ),
    ]
