# Generated by Django 3.0.5 on 2020-06-02 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_auto_20200602_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prompts.Prompt'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prompts.Template'),
        ),
    ]
